### ISSUE TITLE
Veteran and/or Legendary rank consistently not displayed for some users

### ISSUE THREAD

**Issue by Asovrix** [HerpDerpinstine/OGTrustRanks#8]
As stated in the title, I notice that for some users (non-friends and friends) that have _system_trust_legend_ and/or _system_legend_ in their user tags, in-game with this mod active it doesn't show it in any way on the nameplate or anywhere else in menus.
I checked if it's order of tags via VRCX on several people, but it doesn't seem to be the issue here.

**Comment by HerpDerpinstine** [comment]
Just for having system_trust_legend and/or system_legend isn't enough.
They must also have system_trust_trusted as seen here:
https://github.com/HerpDerpinstine/OGTrustRanks/blob/master/OGTrustRanks.cs#L168

**Comment by Asovrix** [comment]
Sorry for the late reply, but users with which I notice "incorrect" rank all have system_trust_trusted in their tags. It must be something else. Another thing I noticed, which probably is related to that is that all of them appear in Socials/details displaying as User, even though if I turn off OGTrustRanks via UIExpansionKit they don't appear as such on nameplates.

**Comment by NataIynn** [comment]
I have the same issue. It shows I'm appearing as legendary, but doesn't show I'm legendary to others or even myself when looking in social.

**Comment by dave-kun** [comment]
@NataIynn Would you be able to provide your VRChat user id or a screenshot of the tags on your VRChat account? I'm not sure if you can do it via VRCX but you can use RubyBot by inviting it to your Discord server and using the "r.vrcuser <your-vrchat-user-id>" command.

https://ruby-core.com/rubybot-invite.html

**Comment by NataIynn** [comment]
![image](https://user-images.githubusercontent.com/28743579/106674528-02f52300-6579-11eb-9b72-1dcf7b8287f7.png)
These are my tags off VRCX, thanks for responding!

**Comment by dave-kun** [comment]
@NataIynn Tags look fine. Ben from the VRCMG Discord mentioned that the showSocialRank prop can be inconsistent, I pushed a new commit to my fork, are you able to pull, compile and test to see if you still experience the issue?

**Comment by NataIynn** [comment]
Compiled and tested. It works correctly now. Thank you for looking into this bug for us. 
![image](https://user-images.githubusercontent.com/28743579/106676195-0a69fb80-657c-11eb-8412-26d26f2217e4.png)

**Comment by Asovrix** [comment]
Is it possible for anyone to publish an updated DLL file since issue appears to be fixed?

**Comment by HerpDerpinstine** [comment]
Will have an updated DLL published here soon.
