### ISSUE TITLE
UI Expansion Kit Pin

### ISSUE THREAD

**Issue by TheChapster** [HerpDerpinstine/OGTrustRanks#9]
It's not a huge deal, but when pinned to UIEK, it only shows the word "Enabled" so can get confusing.
![image](https://user-images.githubusercontent.com/78219705/106290398-55190a00-6242-11eb-946f-04f4f762088d.png)

**Comment by HerpDerpinstine** [comment]
That isn't an issue with OGTrustRanks I don't think.
Looks more like an issue with UIExpansionKit.
